### ISSUE TITLE
Validation error when executing scale

### ISSUE THREAD

**Issue by hdanniel** [aws/amazon-ecs-cli#330]
When executing scale with version 0.6.4 I have the following error:

```
ecs-cli scale - --capability-iam --size 6 --cluster my-cluster --region us-east-1 
ERRO[0000] Error executing 'scale': ValidationError: Invalid input for parameter key SecurityGroupIds. Cannot specify usePreviousValue as true for a parameter key not in the previous template
	status code: 400, request id: 7fd9b5b1-a063-11e7-ad83-6310531d465b 
```

In the cloudformation console there are not events related to this stack update. If I change  the AsgMaxSize directly on the stack, it successfully update and show the events in the console. 
In the template I only have SecurityGroupId not SecurityGroupIds as parameter, but I can see in the cloudformation module that ecs-cli is sending SecurityGroupIds as parameter:

`    ParameterKeySecurityGroup            = "SecurityGroupIds"`

I'm not sure if I need to change the stack template and add SecurityGroupIds, or replace SecurityGroupId. Is because my template is older that ecs-cli and the name of the parameter changed?

Thanks

**Comment by PettitWesley** [comment]
@hdanniel apologies for the inconvenience caused by this issue. I've been able to reproduce it; you are correct- when we updated the cloud formation stack with the new parameter name in #261 it broke backwards compatibility with templates.

Maintaining backwards compatibility is something that we strive for when possible with the ECS CLI, unfortunately, when I changed the parameter name in #261 I forgot that this would break existing templates. So once again, apologies for this issue that you experienced. 

I'd suggest using the Cloud Formation console to update your template to use the new parameter name, or alternatively just use the console to scale your cluster as you mentioned.

**Comment by mguymon** [comment]
👎 Not only is it not backwards compatible, the default cloud formation template created for ECS is still ` SecurityGroupId`

**Comment by PettitWesley** [comment]
@mguymon, once again I'd like to apologize for this unintended breaking of backwards compatibility. 

One possible solution to this problem is to include a flag in the cluster commands that would update the CloudFormation template to the newest version, using the update stack API. 

Thanks for your comments- customer feedback on issues helps us determine which features and bug fixes to prioritize (we notice when issues get a lot of comments or thumbs up/thumbs down- so please never hesitate to post).

@mguymon, can you describe to me what you mean by: 

>  default cloud formation template created for ECS

Do you mean the CloudFormation template created by the ECS Console when you create a cluster?

**Comment by yinshiua** [comment]
Closing this issue, apologies for the inconvenience. Changing anything with CloudFormation now will introduce the same issue for the new template. Let us know if you have other suggestions on how to solve your issue. Thanks!

**Comment by BrianOn99** [comment]
@PettitWesley  I think there should be some migration guide or release note.  I have got stuck, and spent quite a lot of effort to find the issue here.  Could you also list the steps to solve this issue (how to modify existing template) here?

**Comment by PettitWesley** [comment]
@BrianOn99, I'm investigating to see if I can find a better solution to this bug. 

The `ecs-cli scale` command simply allows you to update the number of instances in your cluster; I would recommend simply updating the value for this parameter (`AsgMaxSize`) in the template using the CloudFormation Console.

**Comment by PettitWesley** [comment]
@BrianOn99, @hdanniel, @mguymon, I've fixed this bug in #390. This also allows you to use `ecs-cli scale` on Clusters created by the ECS Console (Web UI).

**Comment by rajanski** [comment]
Maybe I misunderstood something, but seeing this issue closed, I tried to run the latest ecs-cli scale on a CF stack created earlier in the web console. 
I assume I have correctly configured ecs-cli by specifing my CF stack using the  `--cfn-stack-name` parameter.
However, I am still getting the error as described in OP: `Error executing 'scale': ValidationError: Invalid input for parameter key SecurityGroupIds. Cannot specify usePreviousValue as true for a parameter key not in the previous template`

**Comment by PettitWesley** [comment]
@rajanski, are you using the latest version of the ECS CLI, `v1.2.0`?

**Comment by rajanski** [comment]
yes, ecs-cli version 1.2.0 (8d555ea)

**Comment by rajanski** [comment]
Can anybody reproduce above?

**Comment by rajanski** [comment]
It works with 1.2.2
